language: node_js
node_js:
  - 8.0.0
sudo: required
services:
  - docker
env:
  global:
    - NODE_ENV=testing
    - BASE_URL=http://localhost:10010
    - ORIENTDB_HOST=localhost
    - ORIENTDB_PORT=2424
    - ORIENTDB_DB=elvis
    - ORIENTDB_TEST_DB=elvis-testing
    - ORIENTDB_USER=admin
    - ORIENTDB_PASS=admin
    - JWT_SECRET=shhh
    - SESSION_SECRET=hhhh
before_install:
  - docker run -d --name orientdb -p 2424:2424 -e ORIENTDB_ROOT_PASSWORD=root orientdb:2.2.30
  - docker start orientdb
before_script:
  - npm install -g orientjs
  - orientjs db create elvis-testing graph memory -u root -s root
script:
  - npm run lint
  - npm run test
after_success:
  - npm run coverage
