version: '3'
services:
  elvis_api:
    ports:
      - "10010:10010"
  orientdb:
    ports:
      - 2424:2424
      - 2480:2480
    environment:
      - ORIENTDB_ROOT_PASSWORD=$ORIENTDB_ROOT_PASSWORD

