version: '3'
services:
  elvis_api:
    build: .
    env_file: .env
    restart: always
    links:
      - orientdb
    volumes:
      - /var/lib/elvis/rawdata:/rawdata:ro
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "3"
  orientdb:
    image: orientdb:2.2.30
    restart: always
    environment:
      - ORIENTDB_ROOT_PASSWORD=$ORIENTDB_ROOT_PASSWORD
